# Generated by Django 4.2.30 on 2026-08-28 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='pets/')),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=20)),
                ('raca', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('femea', 'Femea')], max_length=10)),
                ('caracteristicas', models.TextField()),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('endereco_texto', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('raio_area_metros', models.PositiveIntegerField(default=400)),
                ('data_desaparecimento', models.DateField()),
                ('descricao', models.TextField()),
                ('contato', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('P', 'Perdido'), ('E', 'Encontrado')], default='P', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Avistamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('descricao', models.TextField(blank=True)),
                ('contato_quem_viu', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamentos', to='pets.pet')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
